name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test-Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.11'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip
      - run: pip install tox-gh-actions tox
      - run: tox
      - uses: codecov/codecov-action@v2
  Lint-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - run: npm i --ignore-scripts
      - run: npm run lint
  Build-Wheel:
    needs:
      - Test-Python
      - Lint-Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - run: pip install build
      - run: npm i
      - run: python -m build .
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
